apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: localhpatestext
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: localhpatest
  metrics:
  - type: External
    external:
      metricName: runtime.node.event_loop.delay.median
      metricSelector:
        matchLabels:
            env: local
      targetAverageValue: 100M # 100ms
