apiVersion: v1
kind: Service
metadata:
  name: localhpatest
  labels:
    component: localhpatest
spec:
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    component: localhpatest
  type: "NodePort"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localhpatest
  labels:
    component: localhpatest
spec:
  replicas: 2
  selector:
    matchLabels:
      component: "localhpatest"
  template:
    metadata:
      labels:
        component: "localhpatest"
      annotations:
        ad.datadoghq.com/localhpatest.check_names: '["localhpatest"]'
        ad.datadoghq.com/localhpatest.init_configs: '[{}]'
        ad.datadoghq.com/localhpatest.instances: '[{}]'
    spec:
      containers:
        - name: localhpatest
          image: "localhpatest:latest"
          imagePullPolicy: "Never"
          env:
          - name: DATADOG_TRACE_AGENT_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_TRACE_PORT
            value: "28126"
          - name: DD_STATSD_PORT
            value: "28125"
          ports:
          - name: http
            containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            timeoutSeconds: 5
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            timeoutSeconds: 5
            initialDelaySeconds: 20